language: objective-c
osx_image: xcode8.2

before_script:
        -cd HabitManager

script:

# - xcodebuild clean && xcodebuild test -project HabitManager\HabitManager.xcodeproj -scheme HabitManager/HabitManager -destination "platform=iOS Simulator,name=iPhone 5s" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO
# - xcodebuild clean && xcodebuild test -project HabitManager\HabitManager.xcodeproj -scheme HabitManager/HabitManager -destination "platform=iOS Simulator,name=iPhone 6" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO
# - xcodebuild clean && xcodebuild test -project HabitManager\HabitManager.xcodeproj -scheme HabitManager/HabitManager -destination "platform=iOS Simulator,name=iPhone 6 Plus" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO
# - xcodebuild clean && xcodebuild test -project HabitManager\HabitManager.xcodeproj -scheme HabitManager/HabitManager -destination "platform=iOS Simulator,name=iPhone 6s" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO
# - xcodebuild clean && xcodebuild test -project HabitManager\HabitManager.xcodeproj -scheme HabitManager/HabitManager -destination "platform=iOS Simulator,name=iPhone 6s Plus" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO
- xcodebuild clean && xcodebuild test -project HabitManager.xcodeproj -scheme HabitManager -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO
- xcodebuild clean && xcodebuild test -project HabitManager.xcodeproj -scheme HabitManager -destination "platform=iOS Simulator,name=iPhone 7 Plus" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO
# - xcodebuild clean && xcodebuild test -project HabitManager\HabitManager.xcodeproj -scheme HabitManager/HabitManager -destination "platform=iOS Simulator,name=iPhone SE" -sdk iphonesimulator10.2  CODE_SIGNING_REQUIRED=NO


